#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=upscayl
VERSION=2.9.1
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
PKG=/tmp/MXNT/package-$PRGNAM
LINK=https://github.com/upscayl/upscayl/releases/download/v2.9.1/upscayl-2.9.1-linux.zip

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt,usr/bin}
cd $PKG/opt
unzip $CWD/$PRGNAM-$VERSION-linux.zip -d $PRGNAM
sed -i 's| --enable-features=UseOzonePlatform --ozone-platform=wayland||;s|-run||' upscayl/resources/org.upscayl.Upscayl.desktop
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cd $PKG
ln -sf /opt/$PRGNAM/$PRGNAM $PKG/usr/bin
install -dm755 $PKG/usr/share/applications
install -dm755 $PKG/usr/share/pixmaps
mv $PKG/opt/$PRGNAM/resources/org.upscayl.Upscayl.desktop "$pkgdir"/usr/share/applications
mv $PKG/opt/$PRGNAM/resources/512x512.png "$pkgdir"/usr/share/pixmaps/org.upscayl.Upscayl.png

echo "       |-----handy-ruler------------------------------------------------------|
upscayl: upscayl (AI Image Upscaler)
upscayl:
upscayl: Free and Open Source AI Image Upscaler.
upscayl:
upscayl:
upscayl:
upscayl:
upscayl:
upscayl:
upscayl:
upscayl:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

/sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
