#!/bin/sh
# Games

# Slackware build script for smc (Secret Maryo Chronicles)

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=smc
VERSION=20140328
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK=https://github.com/mxnt10/Slackware15-Reposity/releases/download/Release/smc-20140328-x86_64.tar.gz

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/install
cd $PKG; tar xvf $CWD/$PRGNAM-$VERSION*.tar.?z*
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

echo '#! /bin/sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/smc/
"/usr/lib/smc/smc-bin" "$@"' > $PKG/usr/bin/smc
chmod +x $PKG/usr/bin/smc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi

( cd usr/share/smc/gui/font ; rm -rf default_bold.ttf )
( cd usr/share/smc/gui/font ; ln -sf /usr/share/fonts/TTF/LiberationSans-Bold.ttf default_bold.ttf )
( cd usr/share/smc/gui/font ; rm -rf default.ttf )
( cd usr/share/smc/gui/font ; ln -sf /usr/share/fonts/TTF/LiberationSans-Regular.ttf default.ttf )" > $PKG/install/doinst.sh

echo "   |-----handy-ruler------------------------------------------------------|
smc: smc (Secret Maryo Chronicles)
smc:
smc: Secret Maryo Chronicles is an Open Source two-dimensional platform
smc: game with a style designed similar to classic sidescroller games such
smc: as Super Mario Bros. It uses the platform independent library SDL
smc: and, since version 0.98, the OpenGL accelerated graphics renderer
smc: from CEGUI. The game is developed in C++.
smc:
smc:
smc:
smc:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
