#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=onnxruntime
VERSION=1.16.0
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
TMP=/var/tmp/MXNT
PKG=$TMP/package-$PRGNAM
LINK1=https://github.com/microsoft/onnxruntime/releases/download/v1.16.0/onnxruntime-linux-x64-1.16.0.tgz
LINK2=https://github.com/microsoft/onnxruntime/archive/refs/tags/v1.16.0.tar.gz

set -e
wget -c $LINK1
wget -O $PRGNAM-$VERSION-source.tar.gz -c $LINK2
rm -rf $TMP
mkdir -p $PKG/{install,usr/{include/$PRGNAM,lib64}}
cd $TMP; tar xvf $CWD/$PRGNAM-linux*-$VERSION.tgz
cd $PRGNAM-linux*-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cp include/* $PKG/usr/include/onnxruntime
cp lib/* $PKG/usr/lib64

cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION-source.tar.gz
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cp -r include/onnxruntime/* $PKG/usr/include/onnxruntime

echo "           |-----handy-ruler------------------------------------------------------|
onnxruntime: onnxruntime (ONNX Runtime)
onnxruntime:
onnxruntime: cross-platform, high performance ML
onnxruntime: inferencing and training accelerator.
onnxruntime:
onnxruntime:
onnxruntime:
onnxruntime:
onnxruntime:
onnxruntime:
onnxruntime:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
