#!/bin/bash

# Slackware build script for lib64openssl1.0.0

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=lib64openssl1.0.0
VERSION=1.1.0j
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
PKG=/tmp/package-openssl10
LINK=https://ftp.nluug.nl/pub/os/Linux/distr/pclinuxos/pclinuxos/apt/pclinuxos/64bit/RPMS.x86_64/lib64openssl1.0.0-1.1.0j-2pclos2019.x86_64.rpm

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/install
cd $PKG; rpm2cpio $CWD/$PRGNAM-$VERSION*.rpm | cpio -idm
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cd usr/lib64
ln -s libcrypto.so.1.0.0 libcrypto.so.1
ln -s libssl.so.1.0.0 libssl.so.1

echo "                 |-----handy-ruler------------------------------------------------------|
lib64openssl1.0.0: lib64openssl1.0.0 (OpenSSL shared libraries v1.0.x)
lib64openssl1.0.0:
lib64openssl1.0.0: These shared libraries provide encryption routines required by
lib64openssl1.0.0: programs such as openssh, bind, sendmail, and many others.
lib64openssl1.0.0:
lib64openssl1.0.0: This product includes software developed by the OpenSSL Project for
lib64openssl1.0.0: use in the OpenSSL Toolkit (http://www.openssl.org). This product
lib64openssl1.0.0: includes cryptographic software written by Eric Young
lib64openssl1.0.0: (eay@cryptsoft.com). This product includes software written by Tim
lib64openssl1.0.0: Hudson (tjh@cryptsoft.com).
lib64openssl1.0.0:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
