#!/bin/sh
# Dependencies

# Slackware build script for libplacebo

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=libplacebo
VERSION=3.120.3
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://code.videolan.org/videolan/libplacebo/-/archive/v3.120.3/libplacebo-v3.120.3.tar.gz

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK

mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$PRGNAM-v$VERSION.tar.?z
cd $PRGNAM-v$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

if [ "${DEBUG:=0}" != 0 ]; then
	NDEBUG=false
	RELEASE=debug
	SLKCFLAGS="$(printf %s "$SLKCFLAGS" | sed 's/-O2/-O0/')"
else
	NDEBUG=true
	RELEASE=plain
fi

sed -i 's/1.4.0/1.3.1/' src/meson.build
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
meson \
  --prefix=/usr \
  --libdir=lib${LIBDIRSUFFIX} \
  -Dstrip=$NDEBUG \
  -Db_ndebug=$NDEBUG \
  -Dbuildtype=$RELEASE \
build
"${NINJA:=ninja}" -C build
DESTDIR=$PKG "$NINJA" -C build install
cp -a LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION

echo "          |-----handy-ruler------------------------------------------------------|
libplacebo: libplacebo (GPU-accelerated video/image rendering primitives library)
libplacebo:
libplacebo: libplacebo is essentially the core rendering algorithms and ideas of
libplacebo: MPV turned into a library.
libplacebo:
libplacebo: Homepage: https://code.videolan.org/videolan/libplacebo
libplacebo:
libplacebo:
libplacebo:
libplacebo:
libplacebo:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-v$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
