#!/bin/sh
# Software

# Slackware build script for mx-conky

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=mx-conky
DATANAM=mx-conky-data
VERSION=21.7
DATAVER=20211226
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) export ARCH=i586 ;;
	arm*) export ARCH=arm ;;
	   *) export ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK1=http://mxrepo.com/mx/repo/pool/main/m/mx-conky/mx-conky_21.7.tar.xz
LINK2=http://mxrepo.com/mx/repo/pool/main/m/mx-conky-data/mx-conky-data_20211226.tar.xz
LINK3=https://raw.githubusercontent.com/mxnt10/Slackware15-Reposity/master/Extra/MX-Conky_21.7_Fix/fix_check_messages.patch

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK1 $LINK2 $LINK3
rm -rf $PKG $TMP/$PRGNAM-$VERSION $TMP/all
mkdir -p $PKG/{install,usr/{bin,doc/$PRGNAM-$VERSION,share/{applications,icons/hicolor/256x256/apps,mx-conky/locale,mx-conky-data/themes}}}
cd $TMP; tar xvf $CWD/${PRGNAM}_${VERSION}.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

patch -Np1 -i $CWD/fix_check_messages.patch

qmake-qt5 -o Makefile mx-conky.pro
make

cp -a help/* $PKG/usr/doc/$PRGNAM-$VERSION
cp -a icons/mx-conky.png $PKG/usr/share/icons/hicolor/256x256/apps
install -Dm 755 mx-conky -t $PKG/usr/bin
cp -a mx-conky.desktop $PKG/usr/share/applications
cp -a translations/*.ts $PKG/usr/share/mx-conky/locale

cd $TMP; tar xvf $CWD/${DATANAM}_${DATAVER}.tar.?z*
cd $DATANAM

cp -a MX* $PKG/usr/share/mx-conky-data/themes
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

echo "        |-----handy-ruler------------------------------------------------------|
mx-conky: mx-conky (conky in the MX Linux)
mx-conky:
mx-conky: MX Conky is a tool used for manipulating detailed
mx-conky: attributes such as color or formats.
mx-conky:
mx-conky:
mx-conky:
mx-conky:
mx-conky:
mx-conky:
mx-conky:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION $TMP/all

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
