#!/bin/sh
# Software

# Slackware build script for nulloy
# Optional: gst-plugins-bad gst-plugins-ugly !

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=nulloy
VERSION=0.8.2_112
SRCVER=0.8.2.pre112
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM-git
LINK=https://github.com/nulloy/nulloy/archive/0.8.2.pre112.tar.gz

[ "$ARCH" = "x86_64" ] && LIBDIRSUFFIX="64" || LIBDIRSUFFIX=""

set -e
wget -c $LINK
rm -rf $PKG $TMP/$PRGNAM-$SRCVER
mkdir -p $PKG/{install,usr/{share/pixmaps,doc/$PRGNAM-$VERSION}}
cd $TMP; tar xvf $CWD/$SRCVER.tar.?z*
cd $PRGNAM-$SRCVER
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

sed -i "6s/lib/lib${LIBDIRSUFFIX}/" configure
sed -i "116s/qmake/qmake-qt5/" configure
sed -i "117s/lrelease/lrelease-qt5/" configure
./configure --no-update-check
make; make INSTALL_ROOT=$PKG install

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
cp -a AUTHORS ChangeLog LICENSE* README* THANKS $PKG/usr/doc/$PRGNAM-$VERSION
install -D -m 0644 ./src/icons/icon.svg $PKG/usr/share/pixmaps/$PRGNAM.svg
for N in 16 22 24 32 48 64 96 128; do
	install -D -m 0644 ./src/icons/icon-$N.png $PKG/usr/share/icons/hicolor/${N}x${N}/apps/$PRGNAM.png
done

echo "      |-----handy-ruler------------------------------------------------------|
nulloy: nulloy (Audio Player)
nulloy:
nulloy: Music player with a waveform progress bar
nulloy:
nulloy:
nulloy:
nulloy:
nulloy: Homepage: https://nulloy.com/
nulloy:
nulloy:
nulloy:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$SRCVER

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
        y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
