#!/bin/sh
# Dependencies

# Slackware build script for rar

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=rar
VERSION=6.12
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

LINK1=https://www.rarlab.com/rar/rarlinux-x32-612.tar.gz
LINK2=https://www.rarlab.com/rar/rarlinux-x64-612.tar.gz

case "$( uname -m )" in
	i?86) LINK=$LINK1; ARCH=i386 ;;
  x86_64) LINK=$LINK2; ARCH=x86_64 ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM

if [ "$ARCH" = "x86_64" ]; then
   LIBDIRSUFFIX="64"
elif [ "$ARCH" = "i386" ]; then
   ARCH=i386
   LIBDIRSUFFIX=""
else
   echo -e "\n Not Support !\n"; exit 1
fi

set -e
wget -c $LINK
rm -rf $PKG $TMP/$PRGNAM
mkdir -p $PKG/{install,usr/{bin,lib${LIBDIRSUFFIX},doc/$PRGNAM-$VERSION},etc}
cd $TMP
tar xvf $CWD/${PRGNAM}linux-*.tar.gz
cd $PRGNAM
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

install -m 0755 rar $PKG/usr/bin
install -m 0755 default.sfx $PKG/usr/lib${LIBDIRSUFFIX}
install -m 0755 unrar $PKG/usr/bin
cat rarfiles.lst > $PKG/etc/rarfiles.lst.new

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
cp -a readme.txt whatsnew.txt license.txt rar.txt order.htm acknow.txt $PKG/usr/doc/$PRGNAM-$VERSION

echo "   |-----handy-ruler------------------------------------------------------|
rar: rar (processes RAR files)
rar:
rar: Rar is a powerful tool for processing RAR archives.
rar:
rar: Homepage: https://www.rarlab.com
rar:
rar: This is a shareware program.  You must buy a license
rar: from Rar Labs if you want to keep using rar.
rar:
rar:
rar:" > $PKG/install/slack-desc

echo 'config() {
  NEW="$1"
  OLD="$(dirname $NEW)/$(basename $NEW .new)"
  # If there is no config file by that name, mv it over:
  if [ ! -r $OLD ]; then
    mv $NEW $OLD
  elif [ "$(cat $OLD | md5sum)" = "$(cat $NEW | md5sum)" ]; then
    # toss the redundant copy
    rm $NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}

config etc/rarfiles.lst.new' > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
