#!/bin/sh

# Slackware build script for xnconvert

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=xnconvert
SRCNAM=XnConvert
VERSION=1.95
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

LINK1=https://download.xnview.com/XnConvert-linux.tgz
LINK2=https://download.xnview.com/XnConvert-linux-x64.tgz

case "$( uname -m )" in
	i?86) LINK=$LINK1; ARCH=i586   ;;
  x86_64) LINK=$LINK2; ARCH=x86_64 ;;
	   *) echo -e "\n Not Support !\n"; exit 1 ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
PKG=/tmp/package-$PRGNAM

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt,usr/{bin,share/{applications,pixmaps},doc/$PRGNAM-$VERSION}}
cd $PKG/opt; tar xvf $CWD/$SRCNAM-linux*.tgz
cd $SRCNAM
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

sed -i -e '4d;5d' -e '3aExec=xnconvert' -e '3aIcon=xnconvert' XnConvert.desktop

cp -a XnConvert.desktop $PKG/usr/share/applications
cp -a xnconvert.png $PKG/usr/share/pixmaps
cp -a license.txt README $PKG/usr/doc/$PRGNAM-$VERSION

cd $PKG
ln -s /opt/$SRCNAM/xnconvert.sh $PKG/usr/bin/xnconvert


echo "         |-----handy-ruler------------------------------------------------------|
xnconvert: xnconvert (the best bulk image converter)
xnconvert:
xnconvert: XnConvert is a fast, powerful and free cross-platform batch image
xnconvert: converter, It allows to automate editing for your massive photo
xnconvert: collections, you can rotate, convert and compress your different
xnconvert: images, photos and pictures easily, and apply over 80 actions.
xnconvert:
xnconvert: https://www.xnview.com/en/xnconvert/
xnconvert:
xnconvert:
xnconvert:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

/sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
