#!/bin/bash

# CheckLink v4.0 - Script para Manutenção dos Links - By Mauricio Ferrari - Copyright 2021

CNT=0
CR1=${CR1:-\\033[1;31m}
CR2=${CR2:-\\033[1;32m}
CR3=${CR3:-\\033[1;33m}
CR4=${CR4:-\\033[1;34m}

echo -e "\n${CR4} Iniciando... \n"
for LNK in `cat PreCompiled Sources Libraries Others`; do
	CNT=$(( ${CNT} + 1 ))
	ST=$( curl -Is ${LNK} | head -n 1 | cut -d' ' -f2 )
	CR=${CR3}
	[ "${ST}" == "404" ] && CR=${CR1}
	[ "${ST}" == "200" ] && CR=${CR2}
	echo -e "${CR4} ${CNT}\t- ${CR}${LNK} : ${ST} \033[0m";
done
echo -e "\n${CR4} Finalizado! \n"; exit 0
