#!/bin/bash

################################################################################
#                                                                              #
#                                                                              #
# Build Get 1.0 - Instalação de Pacotes para o Slackware 15.0                  #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Descrição:                                                                   #
#                                                                              #
# Esse software tem como objetivo facilitar o download e a instalação de       #
# pacotes no Slackware 15.0 através de scripts semelhantes ao SlackBuilds.     #
#                                                                              #
#                                                                              #
# Comandos:                                                                    #
#                                                                              #
# update  - Atualiza a Base de Dados.                                          #
# list    - Lista os Programas da Base de Dados.                               # 
# build   - Gera o Pacote do Programa.                                         #
# install - Gera e Instala o Pacote do Programa.                               #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################
#                                                                              #
#                                                                              #
# ChangeLog:                                                                   #
#                                                                              #
# ## [1.0] - 2021-00-00                                                        #
#                                                                              #
#                                                                              #
# Recursos:                                                                    #
#   - Checagem de: Root, Update, Pacotes Criados e Instalados.                 #
#   - Atualizar Lista de Pacotes.                                              #
#   - Listar os Pacotes Disponíveis.                                           #
#   - Gerar o Pacote dos Programas.                                            #
#   - Instalação dos Pacotes.                                                  #
#                                                                              #
#                                                                              #
################################################################################

################################################################################

# ### Definições ###

################################################################################

F=$1
S=$2
CWD=${PWD}
BUILDDIR="/var/build-get"
BUILDSCR="${BUILDDIR}/packages"
BUILDNAME="build-packages.txt"
BUILDLIST="${BUILDDIR}/${BUILDNAME}"
BUILDLINK="https://raw.githubusercontent.com/MauricioFerrari-NovaTrento/Slackware15-Reposity/master/Scripts"
BUILDURL="${BUILDLINK}/${BUILDNAME}"

################################################################################

# ### Função Info ###

################################################################################

info()
{
echo "
################################################################################
#                                                                              #
#                                                                              #
# Build Get 1.0 - Instalação de Pacotes para o Slackware 15.0                  #
#                                                                              #
# By Mauricio Ferrari                                                          #
#                                                                              #
#                                                                              #
# Descrição:                                                                   #
#                                                                              #
# Esse software tem como objetivo facilitar o download e a instalação de       #
# pacotes no Slackware 15.0 através de scripts semelhantes ao SlackBuilds.     #
#                                                                              #
#                                                                              #
# Comandos:                                                                    #
#                                                                              #
# update  - Atualiza a Base de Dados.                                          #
# list    - Lista os Programas da Base de Dados.                               # 
# build   - Gera o Pacote do Programa.                                         #
# install - Gera e Instala o Pacote do Programa.                               #
#                                                                              #
#                                                                              #
#                            ### Copyright 2021 ###                            #
#                                                                              #
#                                                                              #
################################################################################
"; exit 0
}

################################################################################

# ### Checagens ###

################################################################################

concluido()
{
	cd ${CWD}
	echo -e "\nConcluído !\n"
	exit 0
}

checkroot()
{
	[ "${UID}" != "0" ] && echo -e "\nAlgumas Operações Requerem Root !\n" && exit 1
}

checkstart()
{
	[ ! -e "${BUILDLIST}" ] && echo -e "\nArquivo ${BUILDLIST} não Encontrado! Resolvendo..." && updatelist
}

confirmBUILD()
{
	echo -ne "\nJá foi Gerado uma Versão desse Pacote: ${CKB} !\nManter o Pacote(yes/no)? (default: yes): "
	read N
	[ "${N}" == "no" ] && build
	
	# Se executado o "install" o processo não pode parar por aqui.
	[ "${F}" == "build" ] && echo -e "\nSaindo ...\n" && exit 0
}

confirmINST() 
{ 
	echo -ne "\nJá há uma Versão desse Pacote Instalado: ${CKI} !\nContinuar(yes/no)? (default: yes): "
	read N
	[ "${N}" == "no" ] && echo -e "\nSaindo ...\n" && exit 0

	# Não é necessário a opção de yes.
	# Com um simples "Enter", o progresso irá continuar.
}

checkbuild()
{
	# Alguns pacotes podem ser gerados com letras maiúsculas.
	# Portanto, foi usado grep com "-i".
	CKB=$( ls ${BUILDSCR} 2>/dev/null | grep -iE ^${S}-[0-9] )
	[ "${CKB}" != "" ] && confirmBUILD
	[ "${CKB}" == "" ] && build
}

checkinstall()
{
	# Alguns pacotes podem ser nomeados com letras maiúsculas.
	# Portanto, foi usado grep com "-i".
	CKI=$( ls /var/log/packages 2>/dev/null | grep -iE ^${S}-[0-9] )
	[ "${CKI}" != "" ] && confirmINST
}

################################################################################

# ### Função Atualizar Base de Dados ###

################################################################################

updatelist()
{
	checkroot
	echo -e "\nAtualizando a Base de Dados...\n"
	BAK=${BUILDLIST}-BAK
	[ ! -e "${BUILDDIR}"  ] && mkdir -p ${BUILDDIR}
	[   -e "${BUILDLIST}" ] && mv ${BUILDLIST} ${BAK}
	wget -cq --show-progress -O ${BUILDLIST} ${BUILDURL}
	[ ! -e "${BUILDLIST}" ] && [ -e "${BAK}" ] && mv ${BAK} ${BUILDLIST}
	
	# Se o download da base de dados for bem sucedida, o backup não será mais útil.
	[   -e "${BUILDLIST}" ] && rm -f ${BAK}
	
	# Se o checkstart entrou em ação, o processo não pode parar por aqui.
	[ "${F}" == "update"  ] && concluido
}

################################################################################

# ### Função Listar Programas ###

################################################################################

list()
{
	echo -e "\nListando...\n"
	[ "${S}" == "" ] && cat ${BUILDLIST}
	[ "${S}" != "" ] && grep ${S} ${BUILDLIST}
	concluido
}

################################################################################

# ### Função Gerar Pacotes ###

################################################################################

build()
{
	echo -e "\nGerando o Pacote do Programa...\n"
	[ "${S}" == "" ] && echo -e "Parâmetro Incompleto. Não há um Programa a ser Instalado !\n" && exit 1
	[ ! -e ${BUILDSCR} ] && mkdir ${BUILDSCR}
	cd ${BUILDSCR}

	# Alguns pacotes podem ser gerados com letras maiúsculas.
	# Portanto, foi usado grep com "-i".
	DOWN=$( grep -wiE ${S}. ${BUILDLIST} | head -1 | cut -d" " -f8 )
	[ "${DOWN}" == "" ] && echo -e "Não foi Possível Encontrar o Pacote ${S} na Lista!\n" && exit 1
	wget -cq --show-progress -P ${BUILDSCR} ${BUILDLINK}/${DOWN}
	chmod +x ${BUILDSCR}/${DOWN}
	${BUILDSCR}/${DOWN}

	# Se executado o "install" o processo não pode parar por aqui.
	[ "${F}" == "build" ] && concluido
}

################################################################################

# ### Função Instalar ###

################################################################################

installer()
{
	echo -e "\nIniciando o Processo de instalação...\n"
	checkbuild

	# Alguns pacotes podem ser gerados com letras maiúsculas.
	# Portanto, foi usado grep com "-i".
	PRG=$( ls ${BUILDSCR} | grep -iE ^${S}-[0-9] )
	/sbin/upgradepkg --install-new ${BUILDSCR}/${PRG}
	concluido
}

################################################################################

# ### main ###

################################################################################

[ "${F}" == ""        ] && info
[ "${F}" == "update"  ] && updatelist
 
# Com isso, não há a necessidade de rodar o update da primeira inicialização.
checkstart

[ "${F}" == "list"    ] && list

checkroot
checkinstall # Não precisa instalar os pacotes já instalados no sistema.

[ "${F}" == "build"   ] && checkbuild
[ "${F}" == "install" ] && installer
