#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=mp3gain
VERSION=1.6.2
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}
SRCVER=$( echo $VERSION | sed 's/\./_/g' )

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
TMP=/var/tmp/MXNT
PKG=$TMP/package-$PRGNAM
LINK=https://ufpr.dl.sourceforge.net/project/mp3gain/mp3gain/1.6.2/mp3gain-1_6_2-src.zip

if [ "$ARCH" = "i586" ]; then
	SLKCFLAGS="-O2 -march=i586 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
	SLKCFLAGS="-O2 -march=i686 -mtune=i686"
	LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
	SLKCFLAGS="-O2 -fPIC"
	LIBDIRSUFFIX="64"
else
	SLKCFLAGS="-O2"
	LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK
rm -rf $TMP
mkdir -p $TMP/$PRGNAM $PKG/{install,usr/{bin,doc/$PRGNAM-$VERSION}}
cd $TMP/$PRGNAM; unzip $CWD/$PRGNAM-$SRCVER-src.zip
chown -R root:root .
find -L .  -perm /111 -a \! -perm 755 -a -exec chmod 755 {} \+ -o \
        \! -perm /111 -a \! -perm 644 -a -exec chmod 644 {} \+

sed -i -e "s/^\(CFLAGS.*\)/\1 $SLKCFLAGS/" Makefile

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
make $NUMJOBS
install -s -m0755 -o root -g root $PRGNAM $PKG/usr/bin

cp lgpl.txt $PKG/usr/doc/$PRGNAM-$VERSION

echo "       |-----handy-ruler------------------------------------------------------|
mp3gain: mp3gain (adjusts mp3 files so they have the same volume)
mp3gain:
mp3gain: MP3Gain does not just do peak normalization, as many normalizers
mp3gain: do. Instead, it does some statistical analysis to determine how loud
mp3gain: the file actually sounds to the human ear. Also, the changes MP3Gain
mp3gain: makes are completely lossless. There is no quality lost in the change
mp3gain: because the program adjusts the mp3 file directly, without decoding
mp3gain: and re-encoding.
mp3gain:
mp3gain:
mp3gain:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
