#!/bin/sh
# Software

# Slackware build script for clion

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=clion
SRCNAM=CLion
VERSION=2022.1.1
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://download-cf.jetbrains.com/cpp/CLion-2022.1.1.tar.gz

set -e
wget -c $LINK
rm -rf $PKG $TMP/$PRGNAM-$VERSION
mkdir -p $PKG/{install,opt/$PRGNAM,usr/{bin,share/{applications,pixmaps}}}
cd $TMP; tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cp -rf * $PKG/opt/$PRGNAM
( cd $PKG/usr/bin; ln -sf /opt/$PRGNAM/bin/$PRGNAM.sh $PRGNAM; )
install -D -m0644 bin/$PRGNAM.svg $PKG/usr/share/pixmaps/$PRGNAM.svg

echo "[Desktop Entry]
Name=CLion
GenericName=Text Editor
Comment=A Cross-Platform IDE for C and C++ by JetBrains
Exec=clion
Icon=clion
Type=Application
Terminal=false
Categories=Development;TextEditor;" > $PKG/usr/share/applications/$PRGNAM.desktop

echo "     |-----handy-ruler----------------------------------------------------|
clion: clion (A Cross-Platform IDE for C and C++ by JetBrains)
clion:
clion: Create code that's beautiful and correct. With CLion, potential
clion: code issues are detected instantly, as you type and can be fixed
clion: at the touch of a button, while the IDE correctly handles
clion: the changes.
clion:
clion: https://www.jetbrains.com/clion/
clion:
clion:
clion:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
