#!/bin/sh

# Slackware build script for pycharm

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=pycharm
EDITION=community
VERSION=2022.1.1
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://download.jetbrains.com/python/pycharm-community-2022.1.1.tar.gz

set -e
wget -c $LINK
rm -rf $PKG $TMP/$PRGNAM-$EDITION-$VERSION
mkdir -p $PKG/{install,opt/$PRGNAM,usr/{bin,share/{applications,pixmaps}}}
cd $TMP; tar xvf $CWD/$PRGNAM-$EDITION-$VERSION.tar.?z*
cd $PRGNAM-$EDITION-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cp -rf * $PKG/opt/$PRGNAM
rm -rf $PKG/opt/$PRGNAM/lib/libpty/win $PKG/opt/$PRGNAM/lib/libpty/macosx
find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
( cd $PKG/usr/bin; ln -sf /opt/$PRGNAM/bin/$PRGNAM.sh $PRGNAM; )
install -D -m0644 bin/$PRGNAM.png $PKG/usr/share/pixmaps/$PRGNAM.png

echo "[Desktop Entry]
Name=PyCharm
GenericName=Text Editor
Comment=Powerful Python and Django IDE
Exec=pycharm
Icon=pycharm
Type=Application
Terminal=false
Categories=Development;TextEditor;" > $PKG/usr/share/applications/$PRGNAM.desktop

echo "       |-----handy-ruler------------------------------------------------------|
pycharm: pycharm (Python and Django IDE)
pycharm:
pycharm: PyCharm's smart code editor provides first-class support for Python,
pycharm: JavaScript, CoffeeScript, TypeScript, CSS, popular template languages
pycharm: and more. Take advantage of language-aware code completion, error
pycharm: detection, and on-the-fly code fixes!
pycharm:
pycharm: Homepage: https://www.jetbrains.com/pycharm/
pycharm:
pycharm:
pycharm:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
