#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != "x86_64" ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=vscode
SRCNAM=VSCode
BINNAM=code
VERSION=1.77.3
ARCH=x86_64
ARCHTAR=x64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
PKG=/var/tmp/package-$PRGNAM
LINK=https://update.code.visualstudio.com/1.77.3/linux-x64/stable

set -e
wget -O $SRCNAM-linux-$ARCHTAR-$VERSION.tar.gz -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt/$PRGNAM,usr/{bin,doc/$PRGNAM-$VERSION,share/applications},etc/bash_completion.d}
cd $PKG/opt; tar xvf $CWD/$SRCNAM-linux-$ARCHTAR-$VERSION.tar.gz
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cd $SRCNAM-linux-$ARCHTAR
ln -sf /opt/$SRCNAM-linux-$ARCHTAR/bin/$BINNAM $PKG/usr/bin
install -Dm644 resources/app/resources/linux/code.png $PKG/usr/share/icons/hicolor/1024x1024/apps/code.png
install -Dm644 resources/completions/bash/$BINNAM $PKG/etc/bash_completion.d/$BINNAM
cp -a resources/app/LICENSE* $PKG/usr/doc/$PRGNAM-$VERSION

echo '[Desktop Entry]
Name=VSCode
Exec=/usr/bin/code
Icon=/usr/share/icons/hicolor/1024x1024/apps/code.png
Type=Application
Categories=Development;Programming' > $PKG/usr/share/applications/$PRGNAM.desktop
  
echo '      |-----handy-ruler------------------------------------------------------|
vscode: vscode (Build and debug modern web and cloud applications)
vscode:
vscode: VS Code is a new type of tool that combines the simplicity of a code
vscode: editor with what developers need for their core edit-build-debug
vscode: cycle. Code provides comprehensive editing and debugging support, an
vscode: extensibility model, and lightweight integration with existing tools.
vscode:
vscode:
vscode:
vscode: https://github.com/Microsoft/vscode/
vscode:' > $PKG/install/slack-desc

echo 'if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi' > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
