#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=frequencycpu
VERSION=1.0
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
PKG=/var/tmp/package-$PRGNAM
LINK=https://github.com/mxnt10/FrequencyCPU/archive/refs/tags/v1.0.tar.gz

set -e
wget -c -O $PRGNAM-$VERSION.tar.gz $LINK
rm -rf $PKG
mkdir -p $PKG/{install,usr/{bin,share/{applications,pixmaps},doc/$PRGNAM-$VERSION}}
cd $PKG; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z* --strip=1
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

mv FrequencyCPU $PKG/usr/bin
mv F*quencyCPU.desktop $PKG/usr/share/applications
mv *.png $PKG/usr/share/pixmaps
mv changelog LICENSE README.md $PKG/usr/doc/$PRGNAM-$VERSION

echo "            |-----handy-ruler------------------------------------------------------|
frequencycpu: frequencycpu (frequency cpu tool)
frequencycpu:
frequencycpu: Change frequency and governor of the
frequencycpu: processor.
frequencycpu:
frequencycpu: https://github.com/mxnt10/FrequencyCPU
frequencycpu:
frequencycpu:
frequencycpu:
frequencycpu:
frequencycpu:" > $PKG/install/slack-desc

echo 'if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi' > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
