#!/bin/sh
# Dependencies

# Slackware build script for python3-soupsieve

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=python3-soupsieve
SRCNAM=soupsieve
VERSION=2.3.1
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://github.com/facelessuser/soupsieve/archive/2.3.1/soupsieve-2.3.1.tar.gz

set -e
wget -c $LINK
rm -rf $PKG $TMP/$SRCNAM-$VERSION
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

python3 setup.py install --root=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
cp -a *.md docs/ requirements/ $PKG/usr/doc/$PRGNAM-$VERSION

echo "                 |-----handy-ruler------------------------------------------------------|
python3-soupsieve: python3-soupsieve (A CSS selector implementation for BeautifulSoup)
python3-soupsieve:
python3-soupsieve: Soup Sieve is a CSS selector library designed to be used with
python3-soupsieve: Beautiful Soup 4. It aims to provide selecting, matching, and
python3-soupsieve: filtering using modern CSS selectors.
python3-soupsieve:
python3-soupsieve:
python3-soupsieve:
python3-soupsieve:
python3-soupsieve:
python3-soupsieve:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$SRCNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
