#!/bin/sh
# Dependencies

# Slackware build script for python3-docopt

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=python3-docopt
SRCNAM=docopt
VERSION=0.6.2
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://pypi.python.org/packages/source/d/docopt/docopt-0.6.2.tar.gz

set -e
wget -c $LINK
rm -rf $PKG $TMP/$SRCNAM-$VERSION
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

python3 setup.py install --root=$PKG
cp -a README.rst LICENSE-MIT PKG-INFO $PKG/usr/doc/$PRGNAM-$VERSION

echo '              |-----handy-ruler------------------------------------------------------|
python3-docopt: python3-docopt (Command-line interface description language)
python3-docopt:
python3-docopt: docopt helps you
python3-docopt: * define interface for your command-line app
python3-docopt: * automatically generate parser for it.
python3-docopt:
python3-docopt: Homepage: http://docopt.org/
python3-docopt:
python3-docopt:
python3-docopt:
python3-docopt:' > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$SRCNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0

