#!/bin/sh

# Slackware build script for python3-PyQtWebEngine

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=python3-PyQtWebEngine
SRCNAM=${PRGNAM#*-}
VERSION=5.15.3
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://files.pythonhosted.org/packages/eb/00/f97a8c856ac477bedfcd3fe32f4f886534784bf257106905feaef3cd4a29/PyQtWebEngine-5.15.3.tar.gz


if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK
rm -rf $PKG $TMP/$SRCNAM-$VERSION
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$SRCNAM-$VERSION.tar.?z*
cd $SRCNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

export QTDIR=/usr/lib${LIBDIRSUFFIX}/qt5
export QT5DIR=/usr/lib${LIBDIRSUFFIX}/qt5
export CFLAGS="$SLKCFLAGS"
export CXXFLAGS="$SLKCFLAGS"

python3 configure.py \
  --verbose \
  -q /usr/bin/qmake-qt5 \
  --sip=/usr/bin/sip3 \
  --sip-incdir=$(pkg-config --cflags-only-I python3 | sed -e 's/^-I//')
make; make -j1 install DESTDIR=$PKG INSTALL_ROOT=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
cp -a ChangeLog LICENSE NEWS README $PKG/usr/doc/$PRGNAM-$VERSION

echo "                     |-----handy-ruler------------------------------------------------------|
python3-PyQtWebEngine: python3-PyQtWebEngine (Python3 QtWebEngine Bindings)
python3-PyQtWebEngine:
python3-PyQtWebEngine: PyQtWebEngine is a set of Python bindings for The Qt Company's Qt
python3-PyQtWebEngine: WebEngine libraries. The bindings sit on top of PyQt5 and are
python3-PyQtWebEngine: implemented as a set of three modules. Prior to v5.12 these
python3-PyQtWebEngine: bindings were part of PyQt itself.
python3-PyQtWebEngine:
python3-PyQtWebEngine:
python3-PyQtWebEngine:
python3-PyQtWebEngine:
python3-PyQtWebEngine:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$SRCNAM-$VERSION*

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0

