#!/bin/sh

# Slackware build script for discord

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=discord
VERSION=0.0.15
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://dl.discordapp.net/apps/linux/0.0.15/discord-0.0.15.tar.gz

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt/$PRGNAM,usr/{bin,share/{applications,pixmaps}}}
cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z
cd Discord; chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

ln -sf /opt/$PRGNAM/Discord $PKG/usr/bin/
sed -i "s|/usr/share/discord/||" $PRGNAM.desktop
cp -a * $PKG/opt/$PRGNAM
cp -a $PRGNAM.desktop $PKG/usr/share/applications
cp -a $PRGNAM.png $PKG/usr/share/pixmaps

echo "       |-----handy-ruler------------------------------------------------------|
discord: discord (It's time to ditch Skype and TeamSpeak)
discord:
discord: All-in-one voice and text chat for gamers that's free, secure, and
discord: works on both your desktop and phone. Stop paying for TeamSpeak
discord: servers and hassling with Skype. Simplify your life.
discord:
discord: Homepage: https://discordapp.com/
discord:
discord:
discord:
discord:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
