#!/bin/sh

# Slackware build script for eclipse-jee

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=eclipse-jee
VERSION=4.18
ARCH=x86_64
SRCVERSION=2020-12-R
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK=https://eclipse.c3sl.ufpr.br/technology/epp/downloads/release/2020-12/R/eclipse-jee-2020-12-R-linux-gtk-x86_64.tar.gz

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt/$PRGNAM,usr/{bin,share/{applications,pixmaps},doc/$PRGNAM-$VERSION}}
cd $PKG/opt/$PRGNAM
tar --strip-components=1 -xvf $CWD/$PRGNAM-$SRCVERSION-linux-gtk-x86_64.tar.gz
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

echo "#!/bin/sh
cd \$HOME
/opt/$PRGNAM/eclipse \$@
" > $PKG/usr/bin/$PRGNAM
chmod 0755 $PKG/usr/bin/$PRGNAM

install -D -m 0644 "$PKG/opt/$PRGNAM/$(find . -iname "*javaee-ide_x48.png")" $PKG/usr/share/pixmaps/$PRGNAM.png
mv $PKG/opt/$PRGNAM/configuration/config.ini $PKG/opt/$PRGNAM/configuration/config.ini.new
mv $PKG/opt/$PRGNAM/eclipse.ini $PKG/opt/$PRGNAM/eclipse.ini.new
cp -a readme/*.html $PKG/usr/doc/$PRGNAM-$VERSION

echo '[Desktop Entry]
Type=Application
Exec=env SWT_GTK3=0 eclipse-jee
Name=Eclipse Java EE
GenericName=Eclipse IDE for Java EE Developers
Icon=eclipse-jee
StartupNotify=true
Categories=Qt;KDE;GNOME;Development;GTK;' > $PKG/usr/share/applications/$PRGNAM.desktop

echo '           |-----handy-ruler------------------------------------------------------|
eclipse-jee: eclipse-jee (Eclipse IDE for Java EE Developers)
eclipse-jee:
eclipse-jee: Tools for Java developers creating Java EE and Web applications
eclipse-jee: including a Java IDE, tools for Java EE, JPA, JSF, Mylyn...
eclipse-jee:
eclipse-jee:
eclipse-jee:
eclipse-jee: Homepage: http://www.eclipse.org
eclipse-jee:
eclipse-jee:
eclipse-jee:' > $PKG/install/slack-desc

echo 'config() {
	NEW="$1"
	OLD="$(dirname $NEW)/$(basename $NEW .new)"
	if [ ! -r $OLD ]; then
		mv $NEW $OLD
	elif [ "$(cat $OLD | md5sum)" = "$(cat $NEW | md5sum)" ]; then
		rm $NEW
	fi
}

if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi

config opt/eclipse-jee/configuration/config.ini.new
config opt/eclipse-jee/eclipse.ini.new' > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
