#!/bin/sh

# Slackware build script for flareget

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=flareget
VERSION=5.0.0
TARVER=5.0-1
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ; ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

[ "$ARCH" = "arm" ] && { echo -e "\n Not Support !\n"; exit 1; }
[ "$ARCH" = "x86_64" ] && PKGVER=amd64 || PKGVER=i386

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM 

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK=https://dl.flareget.com/downloads/files/flareget/debs/amd64/flareget_5.0-1_amd64.deb

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,usr/bin}
cd $PKG; ar p $CWD/flareget_${TARVER}_$PKGVER.deb data.tar.xz | tar xJv
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

echo "        |-----handy-ruler------------------------------------------------------|
flareget: flareget (download accelerator)
flareget:
flareget: Multi-threaded download accelerator and manager flareGet is a full 
flareget: featured, multi-threaded and multi-segment download manager and 
flareget: accelerator.
flareget:
flareget: https://flareget.com/
flareget:
flareget:
flareget:
flareget:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

/sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
