#!/bin/sh

# Slackware build script for JDownloader2

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=JDownloader2
VERSION=2.0
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK=https://github.com/MauricioFerrari-NovaTrento/Slackware15-Reposity/releases/download/Release/JDownloader2-2.0.tar.xz

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,opt,usr/{bin,doc/$PRGNAM-$VERSION}}
tar xvf $CWD/$PRGNAM-$VERSION.tar.?z -C $PKG/opt
cd $PKG; chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

ln -sf /opt/$PRGNAM-$VERSION/Launcher $PKG/usr/bin/JDowloader2
ln -sf /opt/$PRGNAM-$VERSION/licenses $PKG/usr/doc/$PRGNAM-$VERSION
cp -a $PKG/opt/$PRGNAM-$VERSION/license*txt $PKG/usr/doc/$PRGNAM-$VERSION
install -D -m 0644 $PKG/opt/$PRGNAM-$VERSION/$PRGNAM.desktop $PKG/usr/share/applications/$PRGNAM.desktop
cd opt/$PRGNAM-$VERSION/themes/standard/org/jdownloader/images/logo
mkdir -p $PKG/usr/share/icons/hicolor/{14x14,15x15,16x16,17x17,18x18,19x19,20x20,48x48,54x54,64x64,128x128,256x256}/apps

for s in {14,15,16,17,18,19,20,48}; do
	size=${s}x${s}
	cp -a logo_${s}_${s}.png $PKG/usr/share/icons/hicolor/$size/apps/$PRGNAM.png || \
	cp -a logo-$size.png $PKG/usr/share/icons/hicolor/$size/apps/$PRGNAM.png
done

for s in {54,64,128,256}; do
	size=${s}x${s}
	cp -a jd_logo_${s}_${s}.png $PKG/usr/share/icons/hicolor/$size/apps/$PRGNAM.png
done

echo "            |-----handy-ruler------------------------------------------------------|
JDownloader2: JDownloader2 (Upload Sites Download)
JDownloader2:
JDownloader2: JDownloader is open source, platform independent and written
JDownloader2: entirely in Java.
JDownloader2:
JDownloader2: Simplifies downloading from hosting sites such as
JDownloader2: Rapidshare.com and Megaupload.com
JDownloader2:
JDownloader2:
JDownloader2:
JDownloader2:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
