#!/bin/sh

# Slackware build script for windscribe

# Copyright 2021 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != "x86_64" ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=windscribe
VERSION=1.4
ARCH=x86_64
BUILD=52
TAG=${TAG:-_mxnt}

WD=$PWD; mkdir -p $PRGNAM; chown -R 1000:users $PRGNAM; cd $PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://assets.staticnetcontent.com/desktop/linux/windscribe-cli-1.4-52.x86_64.rpm

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,etc/rc.d}
cd $PKG; rpm2cpio $CWD/$PRGNAM-cli-${VERSION}-${BUILD}.${ARCH}.rpm | cpio -idmv
rm -rf usr/lib

echo '          |-----handy-ruler------------------------------------------------------|
windscribe: windscribe (Browse the web privately.)
windscribe:
windscribe: Windscribe VPN is a Canada-based provider that promises to help you 
windscribe: browse the web privately. It contains a set of tools that work 
windscribe: together to block ad trackers and web beacons, restore access to 
windscribe: blocked content and help you safeguard your privacy online.
windscribe: You can use Windscribe for free, for as long as you like. With a
windscribe: confirmed email address you get 10GB/month of data.
windscribe:
windscribe: https://www.windscribe.com/
windscribe:' > $PKG/install/slack-desc

echo 'if [ -x /etc/rc.d/rc.windscribe ]; then
    /etc/rc.d/rc.windscribe restart
fi' > $PKG/install/doinst.sh

echo '#!/usr/bin/env bash

pkgnam=windscribe
PID=/var/run/$pkgnam.pid
DAEMON=/usr/bin/windscribe

#
# Function that starts the daemon
#
windscribe_start()
{
  if [ -s $PID ]; then
    echo "$pkgnam is already running: $(cat $PID)"
    exit 1
  fi

  if [ -x $DAEMON ]; then
    $DAEMON start
    pidof $DAEMON > $PID
  fi
}

#
# Function that stops the daemon
#
windscribe_stop()
{
  if [ -s $PID ]; then
    $DAEMON stop
    rm -rf $PID
  else
    echo "$pkgnam is not running."
  fi
}

#
# Function that restarts the daemon
#
windscribe_restart()
{
  windscribe_stop
  sleep 1
  windscribe_start
}

#
# Function that shows the current status of the daemon
#
windscribe_status()
{
  if [ -s $PID ]; then
    echo "$pkgnam is running: $(cat $PID)"
  else
    echo "$pkgnam is not running."
  fi
}

case "$1" in
  start)
    windscribe_start
    ;;
  stop)
    windscribe_stop
    ;;
  restart)
    windscribe_restart
    ;;
  status)
    windscribe_status
    ;;
  *)
    echo $"Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac' > $PKG/etc/rc.d/rc.$PRGNAM

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	[ -e "../Exclamation.mp3" ] && pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY mplayer $WD/Exclamation.mp3 > /dev/null
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
