#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != x86_64 ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=iptvnator
VERSION=0.11.1
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK=https://github.com/4gray/iptvnator/releases/download/v0.11.1/iptvnator_0.11.1_amd64.deb

set -e
wget -c $LINK
rm -rf $PKG
mkdir -p $PKG/{install,usr/bin}
cd $PKG; ar p $CWD/${PRGNAM}_${VERSION}_amd64.deb data.tar.xz | tar xJv
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

ln -sf /opt/iptvnator/iptvnator $PKG/usr/bin/iptvnator
mv $PKG/usr/share/doc $PKG/usr/doc

echo "         |-----handy-ruler------------------------------------------------------|
iptvnator: iptvnator (IPTV Player Application)
iptvnator:
iptvnator: IPTVnator is a video player application that provides support for
iptvnator: the playback of IPTV playlists (m3u, m3u8). The application allows
iptvnator: to import playlists by using remote URLs or per file upload from
iptvnator: the file system. Additionally there is a support of EPG
iptvnator: information XMLTV-based which can be provided by URL.
iptvnator:
iptvnator: https://www.electronjs.org/apps/iptvnator
iptvnator:
iptvnator:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
