#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=libadwaita
VERSION=1.2.2
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) export ARCH=i586 ;;
	arm*) export ARCH=arm ;;
	   *) export ARCH=$( uname -m ) ;;
esac

PATHDIR=$PWD/patch
mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM

CWD=$PWD
TMP=/tmp/MXNT
PKG=$TMP/package-$PRGNAM
LINK1=https://gitlab.gnome.org/GNOME/libadwaita/-/archive/1.2.2/libadwaita-1.2.2.tar.gz

if [ "$ARCH" = "i586" ]; then
        SLKCFLAGS="-O2 -march=i586 -mtune=i686"
        LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
        SLKCFLAGS="-O2 -march=i686 -mtune=i686"
        LIBDIRSUFFIX=""
elif [ "$ARCH" = "aarch64" ]; then
        SLKCFLAGS="-O2"
        LIBDIRSUFFIX="64"
elif [ "$ARCH" = "x86_64" ]; then
        SLKCFLAGS="-O2 -fPIC"
        LIBDIRSUFFIX="64"
else
        SLKCFLAGS="-O2"
        LIBDIRSUFFIX=""
fi

set -e
wget -c $LINK1
rm -rf $TMP
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

NUMJOBS=${NUMJOBS:-" -j$(expr $(nproc) + 1) "}
CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
meson \
  --buildtype=${BUILDTYPE:-release} \
  --infodir=/usr/info \
  --libdir=/usr/lib${LIBDIRSUFFIX} \
  --localstatedir=/var \
  --mandir=/usr/man \
  --prefix=/usr \
  --sysconfdir=/etc \
  -Dgtk_doc=${GTK_DOC:-false} \
  build/

${NINJA:=ninja} $NUMJOBS -v -C build/
DESTDIR=$PKG $NINJA -C build/ install

rm -f $PKG/{,usr/}lib${LIBDIRSUFFIX}/*.la
cp -a AUTHORS HACKING* README* COPYING NEWS $PKG/usr/doc/$PRGNAM-$VERSION

if [[ "$BUILDTYPE" != *"debug"* ]]; then
  find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true
fi

echo "          |-----handy-ruler------------------------------------------------------|
libadwaita: libadwaita (GTK 4 library implementing the GNOME HIG)
libadwaita:
libadwaita: Libadwaita is a GTK 4 library implementing the GNOME HIG,
libadwaita: complementing GTK.
libadwaita:
libadwaita:
libadwaita:
libadwaita:
libadwaita:
libadwaita: Homepage: https://gitlab.gnome.org/GNOME/libadwaita
libadwaita:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
