#!/bin/sh
# Software

# Slackware build script for ckdeps

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=ckdeps
VERSION=6.0_2
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://github.com/mxnt10/ckdeps/archive/refs/tags/v6.0_2.tar.gz

set -e
wget -c -O $PRGNAM-$VERSION.tar.gz $LINK
rm -rf $PKG $TMP/$PRGNAM-$VERSION*
mkdir -p $PKG/install
cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION*
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

install_root=$PKG ./install.sh

echo "      |-----handy-ruler------------------------------------------------------|
ckdeps: ckdeps (check dependencies)
ckdeps:
ckdeps: Searches for installed packages and missing
ckdeps: dependencies in binary executables.
ckdeps:
ckdeps: https://github.com/mxnt10/ckdeps
ckdeps:
ckdeps:
ckdeps:
ckdeps:
ckdeps:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION*

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
