#!/bin/sh

# Slackware build script for grc

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=grc
VERSION=1.13
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

case "$( uname -m )" in
	i?86) ARCH=i586 ;;
	arm*) ARCH=arm ;;
	   *) ARCH=$( uname -m ) ;;
esac

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
TMP=/tmp
PKG=$TMP/package-$PRGNAM
LINK=https://github.com/garabik/grc/archive/refs/tags/v1.13.tar.gz

set -e
wget -c -O $PRGNAM-$VERSION.tar.gz $LINK
rm -rf $PKG $TMP/$PRGNAM-$VERSION
mkdir -p $PKG/{install,usr/doc/$PRGNAM-$VERSION}
cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION

chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .
./install.sh $PKG/usr $PKG

mv $PKG/etc/grc.conf $PKG/etc/grc.conf.new
mv $PKG/etc/profile.d/grc.sh $PKG/etc/profile.d/grc.sh.new
install -m644 grc.zsh $PKG/etc/profile.d/grc.zsh.new
install -m644 grc.fish $PKG/etc/profile.d/grc.fish.new
install -Dm644 _grc $PKG/usr/share/zsh/site-functions/_grc
mv $PKG/usr/share/man $PKG/usr/man
find $PKG/usr/man -type f -exec gzip -9 {} \;
for i in $( find $PKG/usr/man -type l ) ; do ln -s $( readlink $i ).gz $i.gz ; rm $i ; done
cp -r contrib debian/{changelog,copyright} CREDITS INSTALL README.markdown Regexp.txt TODO $PKG/usr/doc/$PRGNAM-$VERSION

echo "   |-----handy-ruler------------------------------------------------------|
grc: grc (generic colouriser)
grc:
grc: grc provides two programs: grc and grcat.  The main is grcat, which
grc: acts as a filter, i.e. taking standard input, colourising it and
grc: writing to standard output. grcat takes as a parameter the name of
grc: configuration file.
grc:
grc: https://github.com/garabik/grc
grc:
grc:
grc:" > $PKG/install/slack-desc

echo "config() {
  NEW=\"\$1\"
  OLD=\"\$(dirname \$NEW)/\$(basename \$NEW .new)\"
  # If there's no config file by that name, mv it over:
  if [ ! -r \$OLD ]; then
    mv \$NEW \$OLD
  elif [ \"\$(cat \$OLD | md5sum)\" = \"\$(cat \$NEW | md5sum)\" ]; then
    # toss the redundant copy
    rm \$NEW
  fi
  # Otherwise, we leave the .new copy for the admin to consider...
}

config etc/grc.conf.new
config etc/profile.d/grc.sh.new
config etc/profile.d/grc.zsh.new
config etc/profile.d/grc.fish.new" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG $TMP/$PRGNAM-$VERSION

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
