#!/bin/sh

# Slackware build script for nosync-browser

# Copyright 2022 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }

PRGNAM=nosync-browser
VERSION=1.0
ARCH=noarch
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM 

CWD=$PWD
PKG=/tmp/package-$PRGNAM
LINK1=https://github.com/biglinux/nosync-browser/archive/refs/tags/1.0.tar.gz
LINK2=https://raw.githubusercontent.com/biglinux/nosync-browser/main/autoenable-manjaro/chrome/usr/share/nosync-browser/chrome

set -e
wget -c -O $PRGNAM-$VERSION.tar.gz $LINK1
rm -rf $PKG
mkdir -p $PKG/{install,usr/{bin,lib,doc/$PRGNAM-$VERSION,share/nosync-browser}}
cd $TMP; tar xvf $CWD/$PRGNAM-$VERSION.tar.?z*
cd $PRGNAM-$VERSION
chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cd src; rm nosync-browser.so; make
install -Dpm755 nosync-browser "$PKG/usr/bin/nosync-browser"
install -Dpm644 nosync-browser.so "$PKG/usr/lib/nosync-browser.so"
cp -a LICENSE $PKG/usr/doc/$PRGNAM-$VERSION
cd $PKG/usr/share/nosync-browser
wget $LINK2
chmod +x chrome

echo "              |-----handy-ruler------------------------------------------------------|
nosync-browser: nosync-browser (Make your browser faster than ever)
nosync-browser:
nosync-browser: Nosync-browser works similar to eatmydata, reducing the number
nosync-browser: of disk writes, but nosync-browser works with Brave, Chrome,
nosync-browser: Opera, Vivaldi...
nosync-browser:
nosync-browser: Just use nosync-browser to open your favorite browser,
nosync-browser: for example: nosync-browser brave-browser
nosync-browser:
nosync-browser:
nosync-browser:" > $PKG/install/slack-desc

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $PKG

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
