#!/bin/sh

# Copyright 2023 Mauricio Ferrari <m10ferrari1200@gmail.com>
# All rights reserved.

[ $UID != 0 ] && { echo -e "\nExecute como Root !\n"; exit 1; }
[ "`uname -m`" != "x86_64" ] && { echo -e "\n Not Support !\n"; exit 1; }

PRGNAM=telegram
SRCDIR=Telegram
SRC=tsetup
VERSION=4.8.1
ARCH=x86_64
BUILD=${BUILD:-1}
TAG=${TAG:-_mxnt}

[ -e "../../_PKGS" ] && { mkdir -p ../../_PKGS/$PRGNAM; chown -R 1000:users ../../_PKGS; cd ../../_PKGS/$PRGNAM; } || {
    mkdir -p PKGS/$PRGNAM; chown -R 1000:users PKGS; cd PKGS/$PRGNAM
}

CWD=$PWD
TMP=/var/tmp/MXNT
PKG=$TMP/package-$PRGNAM
LINK=https://updates.tdesktop.com/tlinux/tsetup.4.8.1.tar.xz

set -e
wget -c $LINK
rm -rf $TMP
mkdir -p $TMP $PKG/{install,opt/$PRGNAM,usr/{bin,share/{applications,pixmaps}}}
cd $TMP; tar xvf $CWD/$SRC.$VERSION.*tar.?z
cd $SRCDIR; chown -R root:root .
chmod -R u+w,go+r-w,a+X-s .

cp -a * $PKG/opt/$PRGNAM
ln -sf /opt/$PRGNAM/Telegram $PKG/usr/bin
wget -c -O $PKG/usr/share/pixmaps/$PRGNAM.png https://github.com/telegramdesktop/tdesktop/raw/dev/Telegram/Resources/art/icon256.png

echo "[Desktop Entry]
Name=Telegram
GenericName=Internet
Comment=Telegram Desktop Chat Client
Icon=telegram
Exec=Telegram -- %u
TryExec=Telegram
Terminal=false
Type=Application
Categories=Network;" > $PKG/usr/share/applications/$PRGNAM.desktop

echo "        |-----handy-ruler------------------------------------------------------|
telegram: telegram (messaging app)
telegram:
telegram: telegram is a cloud-based mobile and desktop messaging app
telegram: with a focus on security and speed.
telegram:
telegram: https://telegram.org/
telegram:
telegram:
telegram:
telegram:
telegram:" > $PKG/install/slack-desc

echo "if [ -x /usr/bin/update-desktop-database ]; then
	/usr/bin/update-desktop-database -q usr/share/applications >/dev/null 2>&1
fi

if [ -x /usr/bin/update-mime-database ]; then
	/usr/bin/update-mime-database usr/share/mime >/dev/null 2>&1
fi

if [ -e usr/share/icons/hicolor/icon-theme.cache ]; then
	if [ -x /usr/bin/gtk-update-icon-cache ]; then
		/usr/bin/gtk-update-icon-cache usr/share/icons/hicolor >/dev/null 2>&1
	fi
fi

if [ -e usr/share/glib-2.0/schemas ]; then
	if [ -x /usr/bin/glib-compile-schemas ]; then
		/usr/bin/glib-compile-schemas usr/share/glib-2.0/schemas >/dev/null 2>&1
	fi
fi" > $PKG/install/doinst.sh

cd $PKG; /sbin/makepkg -l y -c n $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
chown -R 1000:users $CWD/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz
rm -rf $TMP

cd $CWD
[ ${TIME:-0} != 0 ] && TIME="-t $TIME" || TIME=
if [ "${INST:-no}" = "yes" ]; then
	OPTION=y
else
	read $TIME -p "O pacote já pode ser instalado? (y/n) (default=n)" OPTION
fi
case "$OPTION" in
	y|Y) /sbin/upgradepkg --install-new --reinstall $PRGNAM-$VERSION-$ARCH-$BUILD$TAG.txz ;;
esac; exit 0
